apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: czak/launchpad-base:25bea0f06f2e68eb64f692b62929d345
      command:
        - sh
        - -c
        - |
          set -e
          git clone https://github.com/czak/launchpad.git
          cd launchpad/app
          bin/rails s
      envFrom:
        - secretRef:
            name: web-env
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  rules:
    - host: launchpad.czak.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
