apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: worker
      image: czak/launchpad-base:25bea0f06f2e68eb64f692b62929d345
      command:
        - sh
        - -c
        - |
          set -e
          git clone https://github.com/czak/launchpad.git
          cd launchpad/app
          bin/rails runner bin/worker.rb
      envFrom:
        - secretRef:
            name: web-env
