apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: worker
      image: czak/launchpad:39919fe
      command: ["bin/rails", "runner", "bin/worker.rb"]
      envFrom:
        - secretRef:
            name: web-env
