apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/czak/launchpad
          command: ["bin/rails", "runner", "bin/worker.rb"]
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
          envFrom:
            - secretRef:
                name: web-env
      imagePullSecrets:
        - name: ghcr-docker-auth
