version: "2.1"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      PGUSER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: launchpad_development
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres:
    driver: local
