name: Build Docker image

on:
  push:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app
          push: true
          cache-from: type=registry,ref=ruby:2.7.2-alpine,ref=ghcr.io/czak/launchpad:latest
          cache-to: type=inline
          tags: |
            ghcr.io/czak/launchpad:${{ github.sha }}
            ghcr.io/czak/launchpad:latest
      -
        name: Rollout to cluster
        run: |
          kubectl \
            --kubeconfig <(echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode) \
            set image deployment web web=ghcr.io/czak/launchpad:${{ github.sha }}
